package old;

import java.awt.*;
import javax.swing.*;
import lombok.Getter;

public class MainFrame {
  @Getter private JPanel panel1;
  private JLabel testLabel;
  @Getter private JList<PostTeaser> postsList;
  private JScrollPane contentPane;

  public MainFrame() {
    postsList.setCellRenderer(new PostTeaserRenderer());
  }

  {
    // GUI initializer generated by IntelliJ IDEA GUI Designer
    // >>> IMPORTANT!! <<<
    // DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR
   * call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    panel1 = new JPanel();
    panel1.setLayout(new BorderLayout(0, 0));
    testLabel = new JLabel();
    testLabel.setText("test");
    panel1.add(testLabel, BorderLayout.WEST);
    final JSplitPane splitPane1 = new JSplitPane();
    panel1.add(splitPane1, BorderLayout.CENTER);
    final JScrollPane scrollPane1 = new JScrollPane();
    scrollPane1.setHorizontalScrollBarPolicy(31);
    splitPane1.setLeftComponent(scrollPane1);
    postsList = new JList();
    final DefaultListModel defaultListModel1 = new DefaultListModel();
    postsList.setModel(defaultListModel1);
    scrollPane1.setViewportView(postsList);
    contentPane = new JScrollPane();
    splitPane1.setRightComponent(contentPane);
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() {
    return panel1;
  }
}
